#!/bin/bash
# Installs the ANCS (Apple Notification Center Service) bridge daemons.
# Distro-friendly: deps come from pacman, source goes to /opt, no pip.
set -euo pipefail

TARGET_USER="${1:-${SUDO_USER:-$(logname 2>/dev/null || echo root)}}"
SRC="${2:-}"

# With no source directory given, fetch upstream ourselves so this script can
# be run standalone.
CLONED=""
if [ -z "$SRC" ]; then
  SRC="$(mktemp -d)"
  CLONED="$SRC"
  echo "==> Fetching ancs4linux source"
  git clone --depth 1 https://github.com/pzmarzly/ancs4linux.git "$SRC/repo"
  SRC="$SRC/repo"
fi
cleanup() { [ -n "$CLONED" ] && rm -rf "$CLONED"; }
trap cleanup EXIT

if [ ! -d "$SRC/ancs4linux" ]; then
  echo "error: $SRC does not look like an ancs4linux checkout" >&2
  exit 1
fi

echo "==> Installing for user: $TARGET_USER"

echo "==> Installing runtime dependencies"
pacman -S --needed --noconfirm python-dasbus python-typer python-gobject

# ancs4linux discards metadata that ANCS actually sends: the notification
# category, the Silent and Important flags, the subtitle, and the phone's own
# timestamp. This patch surfaces them; without it the plugin still works, but
# category routing and iOS's own urgency signal are unavailable.
PATCH="$(dirname "$(readlink -f "$0")")/patches/ancs4linux-metadata.patch"
if [ -f "$PATCH" ]; then
  echo "==> Applying ANCS metadata patch"
  if git -C "$SRC" apply --check "$PATCH" 2>/dev/null; then
    git -C "$SRC" apply "$PATCH"
    echo "    applied"
  else
    echo "    WARNING: patch did not apply cleanly against this ancs4linux revision."
    echo "    Continuing without it; categories and iOS urgency flags will be unavailable."
  fi
else
  echo "==> No metadata patch found, installing ancs4linux unmodified"
fi

echo "==> Installing ancs4linux to /opt/ancs4linux"
rm -rf /opt/ancs4linux
install -d /opt/ancs4linux
cp -a "$SRC/ancs4linux" /opt/ancs4linux/
cp -a "$SRC/LICENSE.txt" /opt/ancs4linux/ 2>/dev/null || true

echo "==> Creating command wrappers"
make_wrapper() { # $1=binary name  $2=python module path
  cat > "/usr/local/bin/$1" <<WRAP
#!/bin/sh
# Auto-generated by the Omarchy iPhone plugin installer.
PYTHONPATH=/opt/ancs4linux
export PYTHONPATH
exec /usr/bin/python3 -c 'import sys; from $2 import app; sys.exit(app())' "\$@"
WRAP
  chmod 755 "/usr/local/bin/$1"
}
make_wrapper ancs4linux-observer    ancs4linux.observer.main
make_wrapper ancs4linux-advertising ancs4linux.advertising.main
make_wrapper ancs4linux-ctl         ancs4linux.ctl.main

echo "==> Creating ancs4linux group"
groupadd -f ancs4linux
usermod -aG ancs4linux "$TARGET_USER"

echo "==> Installing D-Bus policy"
# /etc/dbus-1/system.d is an includedir in system.conf but is not created by
# the dbus package on Arch, so it may not exist yet.
install -d -m 755 /etc/dbus-1/system.d
install -m 644 "$SRC/autorun/ancs4linux-observer.xml"    /etc/dbus-1/system.d/ancs4linux-observer.conf
install -m 644 "$SRC/autorun/ancs4linux-advertising.xml" /etc/dbus-1/system.d/ancs4linux-advertising.conf

# Group membership only takes effect after a re-login. Granting the user
# directly as well means the bridge works immediately, without logging out.
cat > /etc/dbus-1/system.d/ancs4linux-omarchy-user.conf <<POLICY
<!DOCTYPE busconfig PUBLIC "-//freedesktop//DTD D-BUS Bus Configuration 1.0//EN"
 "http://www.freedesktop.org/standards/dbus/1.0/busconfig.dtd">
<busconfig>
  <policy user="$TARGET_USER">
    <allow send_destination="ancs4linux.Observer"/>
    <allow receive_sender="ancs4linux.Observer"/>
    <allow send_destination="ancs4linux.Advertising"/>
    <allow receive_sender="ancs4linux.Advertising"/>
  </policy>
</busconfig>
POLICY

echo "==> Installing systemd units"
# Upstream units point at /usr/local/bin already; install them as-is minus the
# desktop-integration unit, which the Omarchy plugin replaces (it would
# otherwise raise a second, duplicate toast for every notification).
install -m 644 "$SRC/autorun/ancs4linux-observer.service"    /usr/lib/systemd/system/ancs4linux-observer.service
install -m 644 "$SRC/autorun/ancs4linux-advertising.service" /usr/lib/systemd/system/ancs4linux-advertising.service

systemctl daemon-reload
systemctl reload dbus.service 2>/dev/null || systemctl reload dbus-broker.service 2>/dev/null || true

echo "==> Enabling and starting services"
systemctl enable --now ancs4linux-observer.service
systemctl enable --now ancs4linux-advertising.service

sleep 2
systemctl --no-pager --lines=5 status ancs4linux-observer.service || true
systemctl --no-pager --lines=5 status ancs4linux-advertising.service || true
echo "==> Done"
